const collections = [
  {id: "970110042424610886", slug: "afe", name: "Aliens From Earth", image: require('./images/collections/afe.webp') },
  {id: "903875726418268220", slug: "ballies",name: "Ballies", image: require('./images/collections/ballies.webp') },
  {id: "", slug: "loaded-lions", name: "Loaded Lions", image: require('./images/collections/loadedlions.webp') },
  {id: "905038556140036106", slug:"miner-mole", name: "VVS Miner Mole", image: require('./images/collections/minermole.webp') },
  {id: "896483719295156274", slug:"cronos-chimp-club", name: "Cronos Chimp Club", image: require('./images/collections/chimpclub.webp') },
  {id: "0", slug:"croskull", name: "CroSkull", image: require('./images/collections/croskull.webp') },
  {id: "1009732055648714813", slug:"cronos-cruisers", name: "Cronos Cruisers", image: require('./images/collections/cruisers.webp') },
  {id: "0", slug:"boomer-squad", name: "Boomer Squad", image: require('./images/collections/boomersquad.webp')},
  {id: "1044839682057453639", slug:"eyeball", name: "Eyeball Games", image: require('./images/collections/eyeball.webp') },
  {id: "944556573005590579", slug:"argonauts", name: "Argonauts", image: require('./images/collections/argonauts.webp') },
  {id: "0", slug:"mad-meerkat", name: "Mad Meerkat", image: require('./images/collections/madmeerkat.webp') },
  {id: "1003888475566772295", slug:"cronos-id", name: "Cronos ID", image: require('./images/collections/cronosid.webp') },
  {id: "0", slug:"cronosverse", name: "CronosVerse", image: require('./images/collections/cronosverse.webp') },
  {id: "0", slug:"flaming-phenix", name: "Flaming Phenix Club", image: require('./images/collections/flamingphenix.webp') },
  {id: "912620482031939599", slug:"dgpals", name: "D.G.Pals", image: require('./images/collections/dgpals.webp')},
  {id: "903133867924422677", slug:"cro-crow", name: "CRO Crow", image: require('./images/collections/crocrow.webp') },
  {id: "936221636829519874", slug:"marbleverse", name: "MarbleVerse", image: require('./images/collections/marbleverse.webp') },
  {id: "1014397087116439654", slug:"undead-space-apes", name: "Undead Space Apes", image: require('./images/collections/undeadapes.webp') },
  {id: "921711758484328458", slug:"trooprz", name: "Trooprz", image: require('./images/collections/trooprz.webp') },
  {id: "929744973283340298", slug:"cro-homes", name: "CRO Homes", image: require('./images/collections/crohomes.webp') },
  {id: "911246161233457172", slug:"crxillion", name: "Crxillion", image: require('./images/collections/crxillion.webp') },
  {id: "967089657475121254", slug:"exodus", name: "Exodus", image: require('./images/collections/exodus.webp') },
  {id: "969658754838720556", slug:"crogenft", name: "CrogeNFT", image: require('./images/collections/croge.webp') },
  {id: "0", slug:"bored-candy", name: "Bored Candy", image: require('./images/collections/boredcandy.webp') },
  {id: "911705542995636255", slug:"weird-apes-club", name: "Weird Apes Club", image: require('./images/collections/weirdapes.webp') },
  {id: "1056245905994559595", slug:"cr00ts", name: "Cr00ts", image: require('./images/collections/cr00ts.webp') },
  {id: "0", slug:"cronodesnft", name: "CroNodesNFT", image: require('./images/collections/cronodes.webp') },
  {id: "923642608788578396", slug:"crougar-kingdom", name: "CROugar Kingdom", image: require('./images/collections/crougar.webp') },
  {id: "1072076032624033812", slug:"primate-business", name: "Primate Business", image: require('./images/collections/primatebusiness.webp') },
  {id: "0", slug:"crobots", name: "Crobots", image: require('./images/collections/crobots.webp') },
  {id: "966011090330865704", slug:"baby-alien-division", name: "Baby Alien Division", image: require('./images/collections/bad.webp') },
  {id: "961425677024919614", slug:"aiko-beanz", name: "AIKO BEANZ", image: require('./images/collections/aiko.webp') },
  {id: "0", slug:"aliencro", name: "AlienCRO", image: require('./images/collections/aliencro.webp') },
  {id: "998297452161552424", slug:"crohogs", name: "CroHogs", image: require('./images/collections/crohogs.webp')},
  {id: "0", slug:"blumies", name: "Blumies", image: require('./images/collections/blumies.webp') },
  {id: "0", slug:"VVSFinance", name: "VVS Finance", image: require('./images/collections/vvs.webp') },   
  {id: "994547822701592607", slug:"minted", name: "Minted", image: require('./images/collections/minted.webp') },
  {id: "905933527936278609", slug:"ebisu", name: "Ebisu's Bay", image: require('./images/collections/ebisus.webp') },
  {id: "981654148191772702", slug:"moonflow", name: "MoonfloW", image: require('./images/collections/moonflow.webp') },
  {id: "0", slug:"fulcrom", name: "Fulcrom Finance", image: require('./images/collections/fulcrom.webp') },
  {id: "1042850385670447114", slug:"veno", name: "Veno Finance", image: require('./images/collections/veno.webp') },
  {id: "0", slug:"ferro", name: "Ferro Protocol", image: require('./images/collections/ferro.webp') },
  {id: "0", slug:"tectonic", name: "Tectonic Finance", image: require('./images/collections/tectonic.webp')},
  {id: "0", slug:"the-void", name: "The Void", image: require('./images/collections/void.webp') },
];

export default collections;

export function bySlug(slug) {
  return collections.filter(col => col.slug === slug)[0];
}
